<?php

namespace WildTreckBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportsRepository extends EntityRepository
{
}
